### ISSUE TITLE
Why does payload is too big appear

### ISSUE THREAD

**Issue by shilong1** [leongjinghao/Steganography-Application#1]

**Comment by leongjinghao** [comment]
This warning appears when there is insufficient LSB bit available on the image given to conceal the payload specified. Some available options are as follow:
1. You may wish to increase the value of LSB for bit replacement, note that replacing higher LSB on the image will result in greater distortion
2. Reduce your payload
3. Or you can provide a larger image with more pixels for bit replacement

**Comment by shilong1** [comment]
Thank you for your answer. Maybe it's because I tried to steganograph the video, so this problem occurred.
